Repository sourcegraph/src-cli, pull requests merged in 2021-06, with the labels that each got.

#553 doc: improve developer docs
  DEVELOPMENT.md
  README.markdown
Labels: docs

#552 docker: fix publish workflow
  .github/workflows/docker.yml
  .github/workflows/goreleaser-check.yml
  .github/workflows/goreleaser.yml
  docker/batch-change-volume-workspace/push.py
Labels: team/batchers

#559 Support -insecure-skip-verify flag for LSIF upload
  cmd/src/lsif_upload.go
  cmd/src/lsif_upload_flags.go
  go.mod
  go.sum
Labels: team/code-intelligence

#538 batches: make published field optional
  CHANGELOG.md
  internal/batches/batch_spec.go
  internal/batches/executor/changeset_specs.go
  internal/batches/executor/changeset_specs_test.go
  internal/batches/executor/coordinator.go
  internal/batches/executor/coordinator_test.go
  internal/batches/executor/executor_test.go
  internal/batches/executor/main_test.go
  internal/batches/features.go
  internal/batches/service/service.go
  schema/batch_spec.schema.json
  schema/batch_spec_stringdata.go
Labels: team/batchers
