Repository sourcegraph/src-cli, pull requests merged in 2021-05, with the labels that each got.

#539 Fix skip errors flag
  internal/batches/executor/executor.go
  internal/batches/executor/executor_test.go
Labels: bug, team/batchers

#541 codeintel: Update codeintel/upload package
  cmd/src/lsif_upload.go
  cmd/src/lsif_upload_flags.go
  go.mod
  go.sum
  internal/api/api.go
  internal/api/gzip.go
  internal/api/gzip_test.go
  internal/codeintel/upload.go
Labels: team/code-intelligence

#544 batches: update troubleshooting link URL
  cmd/src/batch_common.go
Labels: team/batchers
