Repository sourcegraph/src-cli, pull requests merged in 2021-03, with the labels that each got.

#483 depend on codeintelutils from sourcegraph/sourcegraph
  cmd/src/lsif_upload.go
  go.mod
  go.sum
  internal/api/api.go
  internal/codeintel/upload.go
Labels: team/code-intelligence

#490 go.mod: rename campaignutils to batch-change-utils
  go.mod
  go.sum
  internal/batches/batch_spec.go
  internal/batches/executor_test.go
Labels: team/batchers

#496 batches: fix batch apply on old Sourcegraph versions
  CHANGELOG.md
  internal/batches/graphql/campaigns.go
Labels: team/batchers

#502 goreleaser: correctly structure the docker section
  .goreleaser.yml
  CHANGELOG.md
Labels: bug, team/batchers
