Repository sourcegraph/src-cli, pull requests merged in 2022-03, with the labels that each got.

#706 batches: fix workspace detection test on M1 Macs
  internal/batches/workspace/workspace_test.go
Labels: team/batchers

#710 lsif upload: Send indexer version witih upload request
  cmd/src/lsif_upload.go
  cmd/src/lsif_upload_flags.go
  go.mod
  go.sum
Labels: team/code-intelligence

#720 search: add a tip about negated searches
  cmd/src/search.go
Labels: docs
