Repository sourcegraph/src-cli, pull requests merged in 2022-07, with the labels that each got.

#794 Cancel reading from stdin on Ctrl-C
  CHANGELOG.md
  cmd/src/batch_common.go
  cmd/src/batch_remote.go
  cmd/src/batch_repositories.go
  cmd/src/batch_validate.go
Labels: team/batchers

#799 remove quotes from upload ID URL
  cmd/src/code_intel_upload.go
Labels: team/code-intelligence, team/language-tools

#803 Fix workspace resolution for non-server-side
  CHANGELOG.md
  cmd/src/batch_common.go
Labels: bug

#804 Don't keep unsupported/ignored repos error for server-side resolution
  CHANGELOG.md
  cmd/src/batch_common.go
  internal/batches/service/build_tasks.go
  internal/batches/service/service.go
  internal/batches/service/service_test.go
Labels: bug
