Repository sourcegraph/src-cli, pull requests merged in 2022-02, with the labels that each got.

#687 batches: make `-f` optional
  CHANGELOG.md
  cmd/src/batch_apply.go
  cmd/src/batch_common.go
  cmd/src/batch_exec.go
  cmd/src/batch_preview.go
  cmd/src/batch_repositories.go
  cmd/src/batch_validate.go
  go.mod
  go.sum
  internal/batches/ui/tty.go
Labels: team/batchers

#688 batches: fail earlier on dotcom
  CHANGELOG.md
  internal/batches/service/service.go
Labels: team/batchers

#692 batches: use the minimum possible goroutines to fetch images
  internal/batches/service/service.go
Labels: team/batchers

#695 batches: fix `src batch apply -f`
  CHANGELOG.md
  cmd/src/batch_apply.go
Labels: bug, team/batchers

#698 all: migrate to github.com/sourcegraph/sourcegraph/lib/errors
  .golangci.yml
  cmd/src/batch_common.go
  cmd/src/batch_exec.go
  cmd/src/batch_remote.go
  cmd/src/batch_repositories.go
  cmd/src/cmd.go
  cmd/src/config.go
  cmd/src/doc.go
  cmd/src/extensions_publish.go
  cmd/src/extsvc.go
  cmd/src/extsvc_edit.go
  cmd/src/lsif_upload_flags.go
  cmd/src/main.go
  cmd/src/repos_delete.go
  cmd/src/search_alert.go
  cmd/src/validate.go
  go.mod
  go.sum
  internal/api/errors.go
  internal/api/gzip.go
  internal/batches/docker/image.go
  internal/batches/executor/coordinator.go
  internal/batches/executor/execution_cache.go
  internal/batches/executor/executor.go
  internal/batches/executor/executor_test.go
  internal/batches/executor/run_steps.go
  internal/batches/features.go
  internal/batches/log/manager.go
  internal/batches/log/task_logger.go
  internal/batches/repozip/fetcher.go
  internal/batches/service/remote.go
  internal/batches/service/service.go
  internal/batches/service/service_test.go
  internal/batches/service/workspaces.go
  internal/batches/ui/tui.go
  internal/batches/workspace/bind_workspace.go
  internal/batches/workspace/bind_workspace_nonwin_test.go
  internal/batches/workspace/bind_workspace_windows_test.go
  internal/batches/workspace/git.go
  internal/batches/workspace/volume_workspace.go
  internal/batches/workspace/volume_workspace_test.go
  internal/batches/workspace/workspace.go
  internal/batches/workspace/workspace_test.go
  internal/cmderrors/errors.go
  internal/exec/expect/expect.go
  internal/servegit/serve.go
  internal/streaming/writer.go
Labels: team/devx, devx/cross-team
